//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetDotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int CartID { get; set; }
        public int GameID { get; set; }
        public int clientID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantité { get; set; }
        public string GameName { get; set; }
        public Nullable<int> numeroCommande { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Game Game { get; set; }
    }
}
